// @navbarPanel
export const SET_NAV_PANLE = 'SET_NAV_PANLE';

// @Navigation
export const SET_GENDER = 'SET_GENDER';
export const SET_GENDER_FIRST_LOAD = 'SET_GENDER_FIRST_LOAD';
export const SET_DIRECTORY = 'SET_DIRECTORY';

// @FilteringDropdown
export const CLEAR_DIRECTORY = 'CLEAR_DIRECTORY';
export const SET_FILTER_DROPDOWN = 'SET_FILTER_DROPDOWN';
export const CLEAR_FILTERS_DROPDOWN = 'CLEAR_FILTERS_DROPDOWN';

// @Products
export const START_FEATCH_PRODUCTS = 'START_FEATCH_PRODUCTS';
export const START_FEATCH_PRODUCT = 'START_FEATCH_PRODUCT';
export const FEATCH_PRODUCTS_SUCCESS = 'FEATCH_PRODUCTS_SUCCESS';
export const FEATCH_PRODUCT_SUCCESS = 'FEATCH_PRODUCT_SUCCESS';
export const SET_FILTERS_OUTPUT = 'SET_FILTERS_OUTPUT';
export const SET_SORT_BY = 'SET_SORT_BY';
export const SET_PRODUCT_IMAGES = 'SET_PRODUCT_IMAGES';
export const SET_PRODUCT_COLOR = 'SET_PRODUCT_COLOR';
export const SELECT_ALL_CHECKE = 'SELECT_ALL_CHECKE';
export const CLEAR_ALL_CHECKE = 'CLEAR_ALL_CHECKE';

// @imageZoom
export const SET_IMAGE_POSITION = 'SET_IMAGE_POSITION';
export const CLEAR_IMAGE_POSITION = 'CLEAR_IMAGE_POSITION';
export const SET_SHOW_LENS = 'SET_SHOW_LENS';
export const SET_IMAGE_INDEX = 'SET_IMAGE_INDEX';

// @Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// @Auth
export const SET_TOKEN = 'SET_TOKEN';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const LOAD_USER_START = 'LOAD_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const UPDATE_USER_PASSWORD_SUCCESS = 'UPDATE_USER_PASSWORD_SUCCESS';
export const UPDATE_USER_PASSWORD_FAIL = 'UPDATE_USER_PASSWORD_FAIL';
export const UPDATE_USER_ADRESS_BOOK_SUCCESS =
  'UPDATE_USER_ADRESS_BOOK_SUCCESS';
export const UPDATE_USER_ADRESS_BOOK_FAIL = 'UPDATE_USER_ADRESS_BOOK_FAIL';
export const DELETE_ADRESS_BOOK_SUCCESS = 'DELETE_ADRESS_BOOK_SUCCESS';
export const DELETE_ADRESS_BOOK_FAIL = 'DELETE_ADRESS_BOOK_FAIL';
export const DELETE_PRODUCT_FROM_CART_SUCCESS =
  'DELETE_PRODUCT_FROM_CART_SUCCESS';
export const DELETE_PRODUCT_FROM_CART_START = 'DELETE_PRODUCT_FROM_CART_START';
export const UPDATE_PRODUCT_TO_WISH_LIST_SUCCESS =
  'UPDATE_PRODUCT_TO_WISH_LIST_SUCCESS';
export const UPDATE_PRODUCT_TO_WISH_LIST_FAIL =
  'UPDATE_PRODUCT_TO_WISH_LIST_FAIL';
export const UPDATE_PRODUCT_CART_START = 'UPDATE_PRODUCT_CART_START';
export const UPDATE_PRODUCT_CART_SUCCESS = 'UPDATE_PRODUCT_CART_SUCCESS';
export const ADD_PRODUCT_TO_CART_SUCCESS = 'ADD_PRODUCT_TO_CART_SUCCESS';
export const ADD_PRODUCT_TO_CART_FAIL = 'ADD_PRODUCT_TO_CART_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// @WishList

export const SET_PRODUCT_WISH_LIST_START = 'SET_PRODUCT_WISH_LIST_START';
export const SET_PRODUCT_WISH_LIST_SUCCESS = 'SET_PRODUCT_WISH_LIST_SUCCESS';

// @Cart
export const SET_TOTAL_AND_QTY = 'SET_TOTAL_AND_QTY';
export const SET_DELELIVERY = 'SET_DELELIVERY';
export const CLEAR_CART = 'CLEAR_CART';

// @Order
export const SET_SHIPPING_ADDRESS = 'SET_SHIPPING_ADDRESS';
export const DELETE_SHIPPING_ADDRESS = 'DELETE_SHIPPING_ADDRESS';
export const SET_CHECKOUT_DELIVERY = 'SET_CHECKOUT_DELIVERY';
export const SET_PAYMENT_STATE = 'SET_PAYMENT_STATE';
